debug: false

recorder:
  directory: /var/lib/bbb-webrtc-recorder
  dirFileMode: 0700
  fileMode: 0600
  writeToDevNull: false
  writeIVFCopy: false
  videoPacketQueueSize: 256
  audioPacketQueueSize: 32
  useCustomSampler: false

pubsub:
  channels:
    subscribe: to-bbb-webrtc-recorder
    publish: from-bbb-webrtc-recorder
  adapter: redis
  adapters:
    redis:
      address: :6379
      network: tcp
      #password: foobared

webrtc:
  rtcMinPort: 24577
  rtcMaxPort: 32768
  jitterBuffer: 256
  jitterBufferPktTimeout: 200
  iceServers:
    - urls: []
# Example turn server
#    - urls:
#        - turn:turnserver.example.org:1234
#      username: webrtc
#      credential: turnpassword

# HTTP server for testing
# (should be disabled in production)
http:
  port: 8080
  enable: false

prometheus:
  enable: false
  listenAddress: 127.0.0.1:3200
